// <auto-generated />
using System;
using Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infra.Migrations.Faturamento
{
    [DbContext(typeof(FaturamentoContext))]
    [Migration("20220706005319_RelacaoAgenciaFaturamento")]
    partial class RelacaoAgenciaFaturamento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Faturamentos.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToView("agencias");
                });

            modelBuilder.Entity("Faturamentos.Faturamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("Faturamento");
                });

            modelBuilder.Entity("Faturamentos.Faturamento", b =>
                {
                    b.HasOne("Faturamentos.Agencia", null)
                        .WithMany("Faturamentos")
                        .HasForeignKey("AgenciaId");
                });

            modelBuilder.Entity("Faturamentos.Agencia", b =>
                {
                    b.Navigation("Faturamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
